%跨被试计算激发态静息态差值矩阵
clc;
clear;
%初始化一个cell数组，其中包含了所有的激发静息差值矩阵
deltamatrixs = {'delta_1_15', 'delta_2_30', 'delta_3_6', 'delta_4_6', ...
    'delta_5_15', 'delta_6_30', 'delta_7_15', 'delta_8_30', ...
    'delta_9_30', 'delta_10_6', 'delta_11_6', 'delta_12_6', ...
    'delta_13_15', 'delta_14_30', 'delta_15_15', 'delta_16_6', ...
    'delta_17_30', 'delta_18_30', 'delta_19_6', 'delta_20_15', ...
    'delta_21_6', 'delta_22_6', 'delta_23_30', 'delta_24_15', ...
    'delta_25_30', 'delta_26_15', 'delta_27_15'};

for delta = 1:length(deltamatrixs)
    

% 初始化路径
    matrix_paths = {
                    ['D:\ssvepnet\sub01wuxiaoliang\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub02xulan\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub03zhouhaobo\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub04qiaohe\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub05zhangyueling\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub06chenyiming2\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub07wangzihao\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub08zhangjingna\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub09wangzhaoyang\matrix\',deltamatrixs{delta},'.csv'], ...
                    ['D:\ssvepnet\sub10laijunjie\matrix\',deltamatrixs{delta},'.csv']
                    };
    num_subjects = length(matrix_paths);
    average_delta_matrix = zeros(size(csvread(matrix_paths{1}))); % 初始化平均差值矩阵

    % 读取数据
    for i = 1:num_subjects
        delta_matrix = csvread(matrix_paths{i});
        average_delta_matrix = average_delta_matrix + delta_matrix; % 累加所有的差值矩阵
    end

    % 计算平均值
    average_delta_matrix = average_delta_matrix / num_subjects;

    % 保存结果
    csvwrite(['D:\ssvepnet\avedeltamatrix\ave_',deltamatrixs{delta}, '.csv'], average_delta_matrix);
end
